### ISSUE TITLE
Too many failed login attempts – show duration

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#378]
When I login about five times with wrong credentials, the login form https://opin-dev.liqd.net/accounts/login/ the login form error says “Too many failed login attempts. Try again later.”. We should higher the threshold to ten times and say in the error message how long users will have to wait.

**Comment by slomo** [comment]
I increased the number of attempts (6a9d3af). The timout is currently 300, I can't change the displayed message in code (because it comes directly from a third party library). There is a hack which would allow to display us  at least a fix value. A dynamic value (eg. wait 225 more seconds) can not be done. If this is really important feel free to reopen.
