### ISSUE TITLE
Login Form Design Review

### ISSUE THREAD

**Issue by nicoladimarco** [liqd/euth_wagtail#56]
Here my suggestions

```
.navbar-default {
    /* DELETE background-color: #f8f8f8; */
    /* DELETE border-color: #e7e7e7; */
}

.skinny-form {
    margin: 55px auto 40px;
    margin: 3.4375rem auto 2.5rem;
    box-shadow: 0 0 150px rgba(0, 0, 0, 0.2);
    float: none;
    padding: 0;
    text-align: center;
}


.nav-tabs {
    border-bottom: 1px solid #ddd;
    font-size: 14px;
}

.skinny-form .btn-cta {
    border-radius: 40px;
    border-radius: 2.5rem;
    padding: 0 20px;
    padding: 0.1rem 1.7rem;
    top: 65px;
    top: 4.0625rem;
    font-weight: bold;
    line-height: 50px;
    margin: -30px auto 0;
    position: relative;
    text-transform: uppercase;

    }


.nav > li > a {
    position: relative;
    display: block;
    padding: 20px 15px;
}

.skinny-form .form-control {
    border-bottom: 1px solid #8C8C8C;
    border-radius: 0;
    padding-left: 0;
    padding-right: 0;
}

#main-menu #language-selector a, #footer #language-selector a {
    color: #337ab7;
}

```

**PLEASE NOTE**
1) in the design I´ve used placeholders, not labels.
placeholder="username"
2) in the design I was showing some inline validation

**Comment by localgrr** [comment]
Thanks @nicoladimarco . I'm not a huge fan of placeholders that replace labels, there's quite a good article about it here https://www.nngroup.com/articles/form-design-placeholders/
You need to have text validation as well as these inline symbols, they do not seem that informative to me.

With the CSS - are you showing all that has changed ? Can you just mark which bits have changed ? Please note if you use Sketch + Zeplin then i can get these values more accurately the first time (instead of guessing) - thanks!

**Comment by nicoladimarco** [comment]
In general I´m also not a huge fan of replacing labels with placeholders text but in this case, since we´re talking about 2/3 basig fields I think it could work well and appear much nicer. If it works for google will work also for us.
I´ve never used sketch but I will consider to ask to buy a licence so we can try it out.

**Comment by MagdaN** [comment]
@nicoladimarco @localgrr can this be closed?
